### ISSUE TITLE
create clubs page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#108]
create a page called 
```clubs-at-cea.html``` under ```src/campus-life/```
with headers and footers from 
```src/contact.html```

and include that in ```webpack.js``` accordingly. 

Make sure you change the ```title``` in html page to ```Clubs | CEA```

**Comment by simpslandyy** [comment]
@abhijithvijayan - I can give this ticket a go.

**Comment by abhijithvijayan** [comment]
Closing.
