### ISSUE TITLE
create a resources page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#109]
create a page called 
```resources.html``` under ```src/```
with headers and footers from 
```src/contact.html```

and include that in ```webpack.js``` accordingly.

Make sure you change the ```title``` in html page to ```Resources | CEA```

**Comment by simpslandyy** [comment]
I'll take this one! :)

**Comment by abhijithvijayan** [comment]
[Merged] #133 
Closing.
