### ISSUE TITLE
create a cea-experience page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#112]
create a page called 
```cea-experience.html``` under ```src/```
with headers and footers from 
```src/contact.html```

and include that in ```webpack.js``` accordingly.

Make sure you change the ```title``` in html page to ```Experiences | CEA```

**Comment by sparkle-sparkle** [comment]
I'll do this one :-)

**Comment by sparkle-sparkle** [comment]
Is it possible to create a menu-component that contains all nav-elements, so this is only in one location and when there are changes you only need to edit this in one file?

I notice that there is no menu item for the 'experience' yet. Do you want me to add one?

**Comment by sparkle-sparkle** [comment]
I think it would be handy to create component for header and footer and include those components in the html files.

**Comment by abhijithvijayan** [comment]
[Merged] #134 
Closing.

**Comment by abhijithvijayan** [comment]
> I think it would be handy to create component for header and footer and include those components in the html files.

@ashikmeerankutty I think you should consider this.
