### ISSUE TITLE
create a news page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#113]
create a page called 
```news.html``` under ```src/news-and-events/```
with headers and footers from 
```src/contact.html```

and include that in ```webpack.js```

Make sure you change the ```title``` in html page to ```News | CEA```

**Comment by trotjr** [comment]
Im doing it

**Comment by trotjr** [comment]
I've done it, PR didn't showed up

**Comment by abhijithvijayan** [comment]
@trotjr I can't find your forked repo!

**Comment by abhijithvijayan** [comment]
@trotjr 

Make changes as said to the repo

Commit your changes
Push 

And create a PR 

We'll verify and merge it.

**Comment by trotjr** [comment]
Ok

**Comment by trotjr** [comment]
I've completed, and submited 
git pull to your repo right?

**Comment by abhijithvijayan** [comment]
there's a button called create pull request on the forked repo on github.

Use that.

**Comment by trotjr** [comment]
Got it!

**Comment by trotjr** [comment]
See if it's right

**Comment by abhijithvijayan** [comment]
@trotjr unfortunately you didn't follow as said on the issue.
Make changes as said and commit and then push.

I'll merge it after

**Comment by abhijithvijayan** [comment]
[Merged] #135 
Closing.

**Comment by ashikmeerankutty** [comment]
@trotjr Happy to hear that this is your first contribution. You can go through these posts to get more knowledge about contributing to open source.
https://www.digitalocean.com/community/tutorial_series/an-introduction-to-open-source
https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

**Comment by trotjr** [comment]
Sorry for the misunderstanding and if I’ve done any delay on your projects, my internet was freaking out so yesterday I couldn’t send any message to answer you.
If you don’t want me to do your issues I’ll understand.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Abhijith V <notifications@github.com>
Enviado: Tuesday, October 9, 2018 1:53:27 PM
Para: ceadoor/cea.ac.in
Cc: TrotJr; Mention
Assunto: Re: [ceadoor/cea.ac.in] create a news page (#113)


Closed #113<https://github.com/ceadoor/cea.ac.in/issues/113>.

**Comment by abhijithvijayan** [comment]
@trotjr No No No, you had errors in the commit. It's fixed and merged now. We have accepted your contribution in fact it's merged. Check #135 

And we only accept 1 contribution from a user for the issues labelled ```hacktoberfest```

Thanks for getting back to us and contributing to the repo.
