### ISSUE TITLE
create a history page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#116]
create a page called 
```our-history.html``` under ```src/about/```
with headers and footers from 
```src/contact.html```

and include that in ```webpack.js``` accordingly.

Make sure you change the ```title``` in html page to ```Our History | CEA```

**Comment by antigui22** [comment]
I'm doing!

**Comment by antigui22** [comment]
Done on #127

**Comment by abhijithvijayan** [comment]
[Commit] #127 Closing.
