### ISSUE TITLE
Creating a commitment page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#117]
create a page called 
```our-commitment.html``` under ```src/about/```
with headers and footers from 
```src/contact.html```

and include that in ```webpack.js``` accordingly.

Make sure you change the ```title``` in html page to ```Our Commitment | CEA```

**Comment by sparkle-sparkle** [comment]
is this one still free?

**Comment by abhijithvijayan** [comment]
@sparkle-sparkle Yes.

**Comment by sparkle-sparkle** [comment]
okay 😃 I would like to pick this one up :-)

**Comment by abhijithvijayan** [comment]
[Merged] #129 
Closing.

**Comment by abhijithvijayan** [comment]
Changes to ```webpack.config.js``` is needed
