### ISSUE TITLE
create a faculty page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#120]
create a page called 
```faculty.html``` under ```src/about/```
with headers and footers from 
```src/contact.html```

and include that in ```webpack.js```

Make sure you change the ```title``` in html page to ```Faculty | CEA```

**Comment by abhijithvijayan** [comment]
Changes to ```webpack.config.js``` is needed

**Comment by Casva** [comment]
I'd like to pick this one up!

**Comment by abhijithvijayan** [comment]
@Casva it's already done.

Just fix that bug.
Thanks

**Comment by abhijithvijayan** [comment]
[Fixed] #137 
Closing.
