### ISSUE TITLE
#200 update readme.md

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#139]
The 200th commit

Include Instagram link in Readme

**Comment by ashikmeerankutty** [comment]
Also add the prettier badge 
[![code style: prettier](https://img.shields.io/badge/code_style-prettier-ff69b4.svg?style=flat-square)](https://github.com/prettier/prettier)

**Comment by abhijithvijayan** [comment]
Happy coding. :grinning:

**Comment by abhijithvijayan** [comment]
[![code style: prettier](https://img.shields.io/badge/code_style-prettier-ff69b4.svg?style=flat)](https://github.com/prettier/prettier)
