### ISSUE TITLE
create a whats-going-on page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#152]
create a page called 
```whats-going-on.html``` under ```src/news-and-events/```
with headers and footers from 
```src/contact.html```

and include that in ```webpack.config.js``` accordingly.

- *create folders as needed*

- Make sure you change the ```title``` in html page to ```What's Going On | CEA```

- *If anyone is on this, first say it here!*

**Comment by mahis929** [comment]
i'll try

**Comment by abhijithvijayan** [comment]
[Merged] #169 
Closing.
