### ISSUE TITLE
Logo Re-Designing/Cloning

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#154]
College's Logo redesigning.

![Present old Logo](https://avatars3.githubusercontent.com/u/34028707?s=400&u=095c1822ef55a754cef46b187da6c8e7b8567b80&v=4)

No psd/png/ai file found
So need to build from scratch

Some of the element in the logo are representations of Government units.

**Comment by Ayaz1997** [comment]
I am working on this

**Comment by abhijithvijayan** [comment]
That's a government logo of Kerala I think

**Comment by Ayaz1997** [comment]
> That's a government logo of Kerala I think

I need to be confirmed otherwise there will be some mistake in the official logo, and something is written under that also.

**Comment by abhijithvijayan** [comment]
@Ayaz1997 just give me some time

I'll find the source of it. 
And BTW thanks for supporting our project.

**Comment by Ayaz1997** [comment]
![image](https://user-images.githubusercontent.com/26507741/46869328-0369cd00-ce49-11e8-9a65-03fbe1374b03.png)
yeah, I got it, its govt of kerela.

> @Ayaz1997 just give me some time
> 
> I'll find the source of it.
> And BTW thanks for supporting our project.

**Comment by abhijithvijayan** [comment]
About the quote below it, we'll go through it.

**Comment by Ayaz1997** [comment]
ya, i think its written govt. of Kerala. Well I'll leave a blank space there and add it when you get confirmed.

> About the quote below it, we'll go through it.

**Comment by abhijithvijayan** [comment]
@Ayaz1997 We're working on confirming if that's actually the logo of Kerala as we have found a lot similar like that.
Just stay put. Let me confirm it.

Thanks

**Comment by Ayaz1997** [comment]
> @Ayaz1997 We're working on confirming if that's actually the logo of Kerala as we have found a lot similar like that.
> Just stay put. Let me confirm it.
> 
> Thanks

Ok, No problem
Welcome

**Comment by abhijithvijayan** [comment]
@Ayaz1997 
It's not the logo we thought it was. It is actually the logo of IHRD available at [Link](http://www.ihrd.ac.in/images/stories/pdf/2016/ihrdlogo2016bw.png) in png.

**Comment by Ayaz1997** [comment]
> @Ayaz1997
> It's not the logo we thought it was. It is actually the logo of IHRD available at [Link](http://www.ihrd.ac.in/images/stories/pdf/2016/ihrdlogo2016bw.png) in png.

Ok, and what about the text below?

**Comment by abhijithvijayan** [comment]
> > @Ayaz1997
> > It's not the logo we thought it was. It is actually the logo of IHRD available at [Link](http://www.ihrd.ac.in/images/stories/pdf/2016/ihrdlogo2016bw.png) in png.
> 
> Ok, and what about the text below?

That we are not sure, yet!
We'll tell you when we get to know about it. You can search for ```cea ihrd logo``` and so to see the best we've got so far. 
and an image is recently stored on the site. [This](http://www.ceadoor.ihrd.ac.in/scan1.jpg)
It can also not give a clear idea about the content.

**Comment by Ayaz1997** [comment]
> > > @Ayaz1997
> > > It's not the logo we thought it was. It is actually the logo of IHRD available at [Link](http://www.ihrd.ac.in/images/stories/pdf/2016/ihrdlogo2016bw.png) in png.
> > 
> > 
> > Ok, and what about the text below?
> 
> That we are not sure, yet!
> We'll tell you when we get to know about it. You can search for `cea ihrd logo` and so to see the best we've got so far.
> and an image is recently stored on the site. [This](http://www.ceadoor.ihrd.ac.in/scan1.jpg)
> It can also not give a clear idea about the content.

Ok, tell me when yo are confirmed. Till then I am preparing only the main logo parts.

**Comment by abhijithvijayan** [comment]
> > > > @Ayaz1997
> > > > It's not the logo we thought it was. It is actually the logo of IHRD available at [Link](http://www.ihrd.ac.in/images/stories/pdf/2016/ihrdlogo2016bw.png) in png.
> > > 
> > > 
> > > Ok, and what about the text below?
> > 
> > 
> > That we are not sure, yet!
> > We'll tell you when we get to know about it. You can search for `cea ihrd logo` and so to see the best we've got so far.
> > and an image is recently stored on the site. [This](http://www.ceadoor.ihrd.ac.in/scan1.jpg)
> > It can also not give a clear idea about the content.
> 
> Ok, tell me when yo are confirmed. Till then I am preparing only the main logo parts.

find this [pdf](http://www.ceadoor.ihrd.ac.in/docs/broschure18.pdf) to zoom in and make an idea about how it is to an extent.

**Comment by Ayaz1997** [comment]
> > > > > @Ayaz1997
> > > > > It's not the logo we thought it was. It is actually the logo of IHRD available at [Link](http://www.ihrd.ac.in/images/stories/pdf/2016/ihrdlogo2016bw.png) in png.
> > > > 
> > > > 
> > > > Ok, and what about the text below?
> > > 
> > > 
> > > That we are not sure, yet!
> > > We'll tell you when we get to know about it. You can search for `cea ihrd logo` and so to see the best we've got so far.
> > > and an image is recently stored on the site. [This](http://www.ceadoor.ihrd.ac.in/scan1.jpg)
> > > It can also not give a clear idea about the content.
> > 
> > 
> > Ok, tell me when yo are confirmed. Till then I am preparing only the main logo parts.
> 
> find this [pdf](http://www.ceadoor.ihrd.ac.in/docs/broschure18.pdf) to zoom in and make an idea about how it is to an extent.

ok

**Comment by abhijithvijayan** [comment]
@Ayaz1997 I think we've got a clean good version of logo to work on. Stay put.

**Comment by abhijithvijayan** [comment]
@Ayaz1997 
[THIS](https://cloud.abhijithvijayan.me/s/XjPxB4B7xmJo7eK) is the best we've got

**Comment by abhijithvijayan** [comment]
They have removed bottom piece of [this](http://www.ihrd.ac.in/images/stories/pdf/2016/ihrdlogo2016bw.png) logo and replaced it with the quote ```MANPOWER DEVELOPMENT``` in a rectangle

That's all.

**Comment by Ayaz1997** [comment]
> They have removed bottom piece of [this](http://www.ihrd.ac.in/images/stories/pdf/2016/ihrdlogo2016bw.png) logo and replaced it with the quote `MANPOWER DEVELOPMENT` in a rectangle
> 
> That's all.

Thank you, thats all I ned. Get your logo today only.

**Comment by abhijithvijayan** [comment]
@Ayaz1997 This is the one. Okay!


Thanks for the support.

**Comment by Ayaz1997** [comment]
> @Ayaz1997 This is the one. Okay!
> 
> Thanks for the support.

Welcome

**Comment by Ayaz1997** [comment]
Done with the Redesign!
![jpeg 1080p](https://user-images.githubusercontent.com/26507741/46877794-48006300-ce5f-11e8-87ed-d557144fc8c8.jpg)

**Comment by abhijithvijayan** [comment]
#197
