### ISSUE TITLE
create a university page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#162]
create a page called 
```university.html``` under ```src/studies/```
with headers and footers from 
```src/contact.html```

and include that in ```webpack.config.js``` accordingly.

- *create folders as needed*

- Make sure you change the ```title``` in html page to ```Universities | CEA```

- *If anyone is on this, first say it here!*

**Comment by nulf** [comment]
Ok if I take this one? Not my first issue but just starting out contributing this hacktoberfest.

**Comment by abhijithvijayan** [comment]
@nulf is now assigned this issue.

**Comment by abhijithvijayan** [comment]
[Merged] #170
Closing.
