### ISSUE TITLE
create university01 page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#163]
create a page called 
```ktu.html``` under ```src/studies/universities/```
with headers and footers from 
```src/contact.html```

and include that in ```webpack.config.js``` accordingly.

- *create folders as needed*

- Make sure you change the ```title``` in html page to ```APJ Abdul Kalam Technological University | CEA```

- *If anyone is on this, first say it here!*

**Comment by pauliax** [comment]
Working on this

**Comment by abhijithvijayan** [comment]
@pauliax is now assigned.
