### ISSUE TITLE
create university02 page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#164]
create a page called 
```cusat.html``` under ```src/studies/universities/```
with headers and footers from 
```src/contact.html```

and then include that in ```webpack.config.js``` accordingly.

- *create folders as needed*

- Make sure you change the ```title``` in html page to ```Cochin University of Science and Technology | CEA```

- *If anyone is on this, first say it here!*

**Comment by mahis929** [comment]
i'm now on this one

**Comment by abhijithvijayan** [comment]
@mahis929 feel free to take it.

**Comment by mahis929** [comment]
check my pull request

**Comment by mahis929** [comment]
check my pull request

**Comment by abhijithvijayan** [comment]
[Merged] #169 
Closing.
