### ISSUE TITLE
create a departments page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#165]
create a page called 
```departments.html``` under ```src/studies/```
with headers and footers from 
```src/contact.html```

and include that in ```webpack.config.js``` accordingly.

- *create folders as needed*

- Make sure you change the ```title``` in html page to ```Departments | CEA```

- *If anyone is on this, first say it here!*

**Comment by mahis929** [comment]
i'm on it

**Comment by abhijithvijayan** [comment]
@mahis929

Please go for other issue in this repo as someone is already on this issue.

**Comment by mahis929** [comment]
check my other comment

**Comment by jcardoz** [comment]
PR Created - please review https://github.com/ceadoor/cea.ac.in/pull/166

**Comment by abhijithvijayan** [comment]
[Merged] 
Closing.
