### ISSUE TITLE
sorting scss files

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#192]
attaching numbers on names of scss files for easiness

**Comment by Fedelaus** [comment]
Apologies for being a pain on this project for you folks.

Could I question the number-in-name system for SCSS files? What are you aiming to achieve?

**Comment by Fedelaus** [comment]
I have just seen the change here and I am a little perplexed, I feel like the change from a semantic name to a `section-1` is harmful rather than helpful, it will become less obvious which page you're working against.

**Comment by abhijithvijayan** [comment]
@Fedelaus Check the PR I submitted.
For the coming developments, the sections for each page will count up to a large number. So keeping it in an orderly manner like I did in PR avoids ambiguity.
I renamed every sectionId to ```section-number``` and renamed scss files accordingly.

Only till now the pages count to >20 sections.

**Comment by abhijithvijayan** [comment]
I don't know if i helps or not. But if it doesn't on the coming dev stage, I'll change it to the way it was, which I hope won't happen.

**Comment by abhijithvijayan** [comment]
@Fedelaus Don't feel that way. We do love other's thoughts/ideas on the project and you're very welcomed to contribute as much as you feel the need to.
