### ISSUE TITLE
Add travis-ci badge to README

### ISSUE THREAD

**Issue by ashikmeerankutty** [ceadoor/cea.ac.in#2]
Add travis-ci badge to README to easily view the build status and navigate to travis page 
[![Build Status](https://travis-ci.org/ceadoor/cea.ac.in.svg?branch=master)](https://travis-ci.org/ceadoor/cea.ac.in)

`[![Build Status](https://travis-ci.org/ceadoor/cea.ac.in.svg?branch=master)](https://travis-ci.org/ceadoor/cea.ac.in)`

**Comment by zeb-stephen-downs** [comment]
@ashikmeerankutty
