### ISSUE TITLE
Adding instagram link to readme.md

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#200]
Replace ```#``` with ```https://www.instagram.com/tracecea?r=nametag``` 

and create a pull request to ```release``` branch.

Checkout the [Contributing.md](https://github.com/ceadoor/cea.ac.in/blob/release/CONTRIBUTING.md) for more info.

**Comment by tomkennedycode** [comment]
I can do this for you.

**Comment by dmaaj** [comment]
done .. added instagram link to readme.md <a href="https://github.com/ceadoor/cea.ac.in/pull/204"> #204</a>

**Comment by abhijithvijayan** [comment]
Closing

**Comment by Shaikh-Raza** [comment]
https://www.instagram.com/technicalfacts02/
