### ISSUE TITLE
add a hover icon-forward effect to font-awesome icons

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#214]
From https://ianlunn.github.io/Hover/

to footer and other links with font awesome icons as badges on hovering

**Comment by kcclemo** [comment]
I can take a look at this if you'd like.

**Comment by abhijithvijayan** [comment]
@kcclemo

Apply that to the footer icons first 

Leave out the rest

**Comment by kcclemo** [comment]
Out of curiosity, is there a coding style guide for this project that I should be made aware of?

**Comment by kcclemo** [comment]
I'm assuming you meant only these links, correct?
![icons-hvr-forward](https://user-images.githubusercontent.com/25205071/47360458-6ac32080-d684-11e8-8c07-bfc54597caed.gif)
