### ISSUE TITLE
about.html debug error

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#248]
![](https://i.imgur.com/A6qyJ1V.png)

**Comment by abhijithvijayan** [comment]
[](https://stackoverflow.com/questions/20175094/uncaught-typeerror-cannot-read-property-top-of-undefined)

**Comment by ashikmeerankutty** [comment]
It's because that element doesn't exist. Since in development stage, it doesn't matter. Adding an if condition can remove the errors.
