### ISSUE TITLE
Navbar Issues

### ISSUE THREAD

**Issue by Athul-CA** [ceadoor/cea.ac.in#252]
Hey,
I am getting a nav bar issue. 
When I click on an item from the dropdown navbar, i get dual dropdowns. I don't know if it is a rendering error, but i get it whenever i click on the options. I'm attaching a screenshot too. 
![screenshot_20190101-120334](https://user-images.githubusercontent.com/40897573/50570760-a03f6500-0dbd-11e9-961b-6d87561202e7.jpg)

**Comment by ashikmeerankutty** [comment]
@Athul-CA  the navbar for mobile sites is not optimized yet. We will be working it on soon Thank you for your feedback

**Comment by ashikmeerankutty** [comment]
#219 duplicate
