### ISSUE TITLE
navbar styling

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#41]
adding hover based navbar with content and links embedded

**Comment by DinahLin** [comment]
Can I work on this project?

**Comment by abhijithvijayan** [comment]
Sure Why not!

**Comment by abhijithvijayan** [comment]
Sliding navbar content like in this [example](https://designshack.net/tutorialexamples/sliding-content-box/index.html)

**Comment by nwyll** [comment]
I will take a stab at this

**Comment by abhijithvijayan** [comment]
>           I will take a stab at this. Which navbar do you want to be hover-based - the very top with the language selection and login or the main navbar with Home, About, Courses ... etc?

The main navbar to be expanded like to 25vh to include headings and links accordingly

**Comment by abhijithvijayan** [comment]
@nwyll @ashikmeerankutty is currently working on it.

**Comment by abhijithvijayan** [comment]
#215
