### ISSUE TITLE
glitch in carousel pointer in Edge, Mozilla browsers

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#42]

**Comment by abhijithvijayan** [comment]
workarounds

Firefox - replace with svg icons from [here](https://www.flaticon.com/)
Edge uses the path relative to css file, while IE uses the path relative to html file.

**Comment by ashikmeerankutty** [comment]
#44 replaces png icons with SVG icons

**Comment by abhijithvijayan** [comment]
fixed
