### ISSUE TITLE
top navbar visibilty issue on other pages

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#84]
![](https://i.imgur.com/C8gi9nQ.png)

## which should be like this

 ![](https://i.imgur.com/cyMliLy.png)

on pages like https://ceadoor.github.io/cea.ac.in/contact

**Comment by ananthuc73** [comment]
Can you please explain it further?

**Comment by abhijithvijayan** [comment]
> Can you please explain it further?

The top navbar( the one in blue) is not visible on pages like [contact.html](https://ceadoor.github.io/cea.ac.in/contact) or [administration.html](https://ceadoor.github.io/cea.ac.in/administration)

**Comment by taranvohra** [comment]
I'll handle it
