### ISSUE TITLE
creating news and events page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#94]
create a page called 
```news-and-events.html``` under ```src/```
with headers and footers from 
```src/administration.html```

and include that in ```webpack.js```

Make sure you change the ```title``` in html page to ```News and Events | CEA```

**Comment by darrenrector91** [comment]
I can take this

**Comment by abhijithvijayan** [comment]
> I can take this

Sorry. We're taking one simple commit from each just to ensure everyone gets a part of it. You can find issues marked as ```good first issue``` or ```hacktoberfest``` in other repos as well.

Thanks for your time.

**Comment by abyabrkal** [comment]
I will work on this. Please confirm @abhijithvijayan.

**Comment by abhijithvijayan** [comment]
Sure @abyabrkal

**Comment by abhijithvijayan** [comment]
@abyabrkal Sorry, one of the guys is working on it.

**Comment by abhijithvijayan** [comment]
#101 Closing.
