### ISSUE TITLE
creating academic-programs page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#95]
create a page called 
```academic-programs.html``` under ```src/studies/```
with headers and footers from 
```src/administration.html```

and include that in ```webpack.js```

**Comment by darrenrector91** [comment]
I can do this too!

**Comment by justvidyadhar** [comment]
Done. Please accept the Pull request.

**Comment by abhijithvijayan** [comment]
[Commit] #97 

Closing.
