### ISSUE TITLE
create stories page

### ISSUE THREAD

**Issue by abhijithvijayan** [ceadoor/cea.ac.in#96]
create a page called 
```stories.html``` under ```src/cea-experience/```
with headers and footers from 
```src/contact.html```

and include that in ```webpack.js``` accordingly.

Make sure you change the ```title``` in html page to ```Student Stories | CEA```

**Comment by harryandriyan** [comment]
I'll take it

**Comment by harryandriyan** [comment]
I make pull req, please check it @abhijithvijayan

**Comment by abhijithvijayan** [comment]
Closing.
